version: '2'
services:

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "notifications"
      POSTGRES_USER: "notifications_user"
      POSTGRES_PASSWORD: "123456789-p"
    ports:
      - "5432:5432"

  db_migrator:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['python', 'models.py']
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - C_FORCE_ROOT=true
      - POSTGRESQL_USER=notifications_user
      - POSTGRESQL_PASSWORD=123456789-p
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DB=notifications

    depends_on:
      - postgres

  redis:
    image: redis
    ports:
    - "6379:6379"
    volumes:
        - ./data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master

  celery-beat:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['celery', '-A', 'tasks', 'beat', '-l', 'info']
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
    depends_on:
      - redis
      - db_migrator

  celery-worker:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['celery', '-A', 'tasks', 'worker', '-l', 'info']
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - C_FORCE_ROOT=true
      - TELEGRAM_API_TOKEN=123456789
      - POSTGRESQL_USER = notifications_user
      - POSTGRESQL_PASSWORD = 123456789-p
      - POSTGRESQL_HOST = postgres
      - POSTGRESQL_PORT = 5432
      - POSTGRESQL_DB = notifications

    depends_on:
      - redis
      - db_migrator

  telegram-bot:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['python', '-u', 'telegram_controller.py']
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - C_FORCE_ROOT=true
      - TELEGRAM_API_TOKEN=123456789
      - POSTGRESQL_USER=notifications_user
      - POSTGRESQL_PASSWORD=123456789-p
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DB=notifications

    depends_on:
      - redis
      - db_migrator